// Stage 1 nutrition scoring: seed data for `nutrition_food_aliases`.
//
// The mapping covers two sources:
//   1. The 100 distinct name_zh values from existing expense_items (mapped
//      against themselves or close substrings).
//   2. ~200 Chinese-common foods organised by category, used to bootstrap
//      matching before the user encounters them in receipts.
//
// The seeder (`scripts/seed-nutrition.ts`) uses `INSERT OR IGNORE` so this
// file is idempotent: re-running it won't overwrite rows the user has
// overridden in the UI.

import type { NutritionCategory } from "@/db/schema";

export type SeedAlias = {
  rawPattern: string;
  category: NutritionCategory;
};

const V = "蔬菜";
const SV = "淀粉类蔬菜";
const F = "水果";
const G = "全谷物";
const R = "精制谷物";
const L = "豆类";
const N = "坚果";
const S = "香料";
const A = "动物性";
const O = "油脂";
const B = "含糖饮料";
const P = "加工肉";
const D = "甜点";
const U = "未分类";

export const seedAliases: ReadonlyArray<SeedAlias> = [
  // === 100 from existing distinct names ===
  { rawPattern: "330ml清爽原味汽水", category: B },
  { rawPattern: "Lady M", category: D },
  { rawPattern: "蛋糕", category: D },
  { rawPattern: "三文鱼", category: A },
  { rawPattern: "五花肉", category: A },
  { rawPattern: "五花超大肉", category: A },
  { rawPattern: "卤汁调料", category: S },
  { rawPattern: "老卤汁", category: S },
  { rawPattern: "前腿肉", category: A },
  { rawPattern: "猪瘦肉", category: A },
  { rawPattern: "鸡腿肉丁", category: A },
  { rawPattern: "羔羊肉", category: A },
  { rawPattern: "基围虾", category: A },
  { rawPattern: "脆毛肚", category: A },
  { rawPattern: "花鲢鱼", category: A },
  { rawPattern: "薄盐三文鱼", category: A },
  { rawPattern: "三文鱼扒", category: A },
  { rawPattern: "猪大肠", category: A },
  { rawPattern: "猪梅花肉", category: A },
  { rawPattern: "猪肉丝", category: A },
  { rawPattern: "鸡腿肉", category: A },
  { rawPattern: "无蔗糖益生菌酸奶", category: A },
  { rawPattern: "益生菌酸奶", category: A },
  { rawPattern: "酸奶", category: A },
  { rawPattern: "卷心菜", category: V },
  { rawPattern: "青菜", category: V },
  { rawPattern: "青甘蓝", category: V },
  { rawPattern: "地瓜叶", category: V },
  { rawPattern: "番薯叶", category: V },
  { rawPattern: "红洋葱", category: S },
  { rawPattern: "土豆", category: SV },
  { rawPattern: "核桃拿破仑", category: D },
  { rawPattern: "坚果拿破仑", category: D },
  { rawPattern: "大闸蟹", category: A },
  { rawPattern: "谷物鸡蛋", category: A },
  { rawPattern: "草鸡蛋", category: A },
  { rawPattern: "鸡蛋", category: A },
  { rawPattern: "小皇冠西瓜", category: F },
  { rawPattern: "西瓜", category: F },
  { rawPattern: "小米椒", category: V },
  { rawPattern: "黄牛吊龙", category: A },
  { rawPattern: "潮汕火锅片", category: A },
  { rawPattern: "亚麻籽油", category: O },
  { rawPattern: "小香葱", category: S },
  { rawPattern: "川式卤料", category: S },
  { rawPattern: "平菇", category: V },
  { rawPattern: "番茄罐头", category: V },
  { rawPattern: "番茄", category: V },
  { rawPattern: "小番茄", category: V },
  { rawPattern: "圣女果", category: V },
  { rawPattern: "西红柿", category: V },
  { rawPattern: "茄意欧", category: V },
  { rawPattern: "冷鲜肉馅", category: A },
  { rawPattern: "黑猪", category: A },
  { rawPattern: "散养", category: A },
  { rawPattern: "无乳糖牛奶", category: A },
  { rawPattern: "全脂牛奶", category: A },
  { rawPattern: "牛奶", category: A },
  { rawPattern: "白蘑菇", category: V },
  { rawPattern: "杏鲍菇", category: V },
  { rawPattern: "椰子水", category: F },
  { rawPattern: "欧芹", category: S },
  { rawPattern: "金枕榴莲", category: F },
  { rawPattern: "榴莲", category: F },
  { rawPattern: "泰森", category: A },
  { rawPattern: "鸡大胸", category: A },
  { rawPattern: "洋葱", category: S },
  { rawPattern: "红宝石莲雾", category: F },
  { rawPattern: "莲雾", category: F },
  { rawPattern: "海带苗", category: V },
  { rawPattern: "海带", category: V },
  { rawPattern: "牛油火锅底料", category: S },
  { rawPattern: "醇香牛油火锅底料", category: S },
  { rawPattern: "海底捞醇香牛油火锅底料", category: S },
  { rawPattern: "牛油果油", category: O },
  { rawPattern: "芥菜馄饨", category: A },
  { rawPattern: "荠菜馄饨", category: A },
  { rawPattern: "胡萝卜", category: V },
  { rawPattern: "番茄膏", category: V },
  { rawPattern: "白葡萄酒", category: B },
  { rawPattern: "葡萄酒", category: B },
  { rawPattern: "酒", category: B },
  { rawPattern: "榴莲软心巴斯克", category: D },
  { rawPattern: "秋葵", category: V },
  { rawPattern: "猪肉糜", category: A },
  { rawPattern: "老姜", category: S },
  { rawPattern: "苹果", category: F },
  { rawPattern: "菠菜", category: V },
  { rawPattern: "葱油花卷", category: R },
  { rawPattern: "花卷", category: R },
  { rawPattern: "螺丝椒", category: V },
  { rawPattern: "蟹味菇", category: V },
  { rawPattern: "裸麦", category: G },
  { rawPattern: "坚果果干面包", category: G },
  { rawPattern: "西兰花", category: V },
  { rawPattern: "西瓜蜜薯", category: SV },
  { rawPattern: "蜜薯", category: SV },
  { rawPattern: "笋丁鲜肉大馄饨", category: A },
  { rawPattern: "鲜肉大馄饨", category: A },
  { rawPattern: "大馄饨", category: A },
  { rawPattern: "马兰头鲜肉大馄饨", category: A },
  { rawPattern: "贝贝南瓜", category: SV },
  { rawPattern: "南瓜", category: SV },
  { rawPattern: "肥牛卷", category: A },
  { rawPattern: "胸腩", category: A },
  { rawPattern: "迷迭香", category: S },
  { rawPattern: "酱猪肝", category: A },
  { rawPattern: "猪肝", category: A },
  { rawPattern: "鸡胗", category: A },
  { rawPattern: "鸡里脊", category: A },
  { rawPattern: "里脊", category: A },
  { rawPattern: "麒麟奶油西瓜", category: F },
  { rawPattern: "奶油西瓜", category: F },
  { rawPattern: "黑椒鸡腿排", category: A },
  { rawPattern: "鸡腿排", category: A },
  { rawPattern: "黑胡椒", category: S },
  { rawPattern: "黑金刚莲雾", category: F },
  { rawPattern: "黑麦芽欧包", category: G },
  { rawPattern: "欧包", category: G },
  { rawPattern: "麦芽欧包", category: G },
  { rawPattern: "牛肉片", category: A },
  { rawPattern: "黄牛肉", category: A },
  { rawPattern: "嫩牛肉", category: A },
  { rawPattern: "鲜香菇", category: V },
  { rawPattern: "香菇", category: V },
  { rawPattern: "香葱", category: V },
  { rawPattern: "高盐", category: A },
  { rawPattern: "支出", category: U },
  { rawPattern: "微信转账", category: U },
  { rawPattern: "淘宝商品", category: U },
  { rawPattern: "怡宝", category: U },
  { rawPattern: "娃哈哈", category: U },
  { rawPattern: "饮用水", category: U },
  { rawPattern: "纯净水", category: U },
  { rawPattern: "盒马超市", category: U },
  { rawPattern: "海底捞", category: U },

  // === Chinese-common extension: vegetables ===
  { rawPattern: "白菜", category: V },
  { rawPattern: "大白菜", category: V },
  { rawPattern: "小白菜", category: V },
  { rawPattern: "娃娃菜", category: V },
  { rawPattern: "油麦菜", category: V },
  { rawPattern: "生菜", category: V },
  { rawPattern: "芹菜", category: V },
  { rawPattern: "韭菜", category: V },
  { rawPattern: "苋菜", category: V },
  { rawPattern: "蒿子秆", category: V },
  { rawPattern: "豆苗", category: V },
  { rawPattern: "豌豆苗", category: V },
  { rawPattern: "莴笋", category: V },
  { rawPattern: "茭白", category: V },
  { rawPattern: "莲藕", category: V },
  { rawPattern: "藕", category: V },
  { rawPattern: "山药", category: SV },
  { rawPattern: "红薯", category: SV },
  { rawPattern: "紫薯", category: SV },
  { rawPattern: "紫甘蓝", category: V },
  { rawPattern: "茄子", category: V },
  { rawPattern: "西红柿", category: V },
  { rawPattern: "彩椒", category: V },
  { rawPattern: "青椒", category: V },
  { rawPattern: "黄瓜", category: V },
  { rawPattern: "冬瓜", category: V },
  { rawPattern: "苦瓜", category: V },
  { rawPattern: "丝瓜", category: V },
  { rawPattern: "佛手瓜", category: V },
  { rawPattern: "豇豆", category: V },
  { rawPattern: "四季豆", category: V },
  { rawPattern: "西葫芦", category: V },
  { rawPattern: "茼蒿", category: V },
  { rawPattern: "豆芽", category: V },
  { rawPattern: "蒜苗", category: S },
  { rawPattern: "蒜苔", category: S },
  { rawPattern: "蒜头", category: S },
  { rawPattern: "大蒜", category: S },
  { rawPattern: "蒜瓣", category: S },
  { rawPattern: "大葱", category: S },
  { rawPattern: "生姜", category: S },
  { rawPattern: "红椒", category: V },
  { rawPattern: "莴苣", category: V },
  { rawPattern: "紫苏", category: S },
  { rawPattern: "香菜", category: S },
  { rawPattern: "木耳", category: V },
  { rawPattern: "银耳", category: V },
  { rawPattern: "黑木耳", category: V },
  { rawPattern: "秋耳", category: V },

  // === Chinese-common extension: fruits ===
  { rawPattern: "橙子", category: F },
  { rawPattern: "橘子", category: F },
  { rawPattern: "蜜橘", category: F },
  { rawPattern: "砂糖橘", category: F },
  { rawPattern: "柚子", category: F },
  { rawPattern: "柠檬", category: F },
  { rawPattern: "葡萄", category: F },
  { rawPattern: "提子", category: F },
  { rawPattern: "草莓", category: F },
  { rawPattern: "樱桃", category: F },
  { rawPattern: "车厘子", category: F },
  { rawPattern: "桃子", category: F },
  { rawPattern: "水蜜桃", category: F },
  { rawPattern: "杏", category: F },
  { rawPattern: "李子", category: F },
  { rawPattern: "梨", category: F },
  { rawPattern: "雪梨", category: F },
  { rawPattern: "鸭梨", category: F },
  { rawPattern: "柿子", category: F },
  { rawPattern: "石榴", category: F },
  { rawPattern: "猕猴桃", category: F },
  { rawPattern: "奇异果", category: F },
  { rawPattern: "芒果", category: F },
  { rawPattern: "木瓜", category: F },
  { rawPattern: "菠萝", category: F },
  { rawPattern: "凤梨", category: F },
  { rawPattern: "火龙果", category: F },
  { rawPattern: "山竹", category: F },
  { rawPattern: "荔枝", category: F },
  { rawPattern: "龙眼", category: F },
  { rawPattern: "桂圆", category: F },
  { rawPattern: "哈密瓜", category: F },
  { rawPattern: "香瓜", category: F },
  { rawPattern: "蓝莓", category: F },
  { rawPattern: "树莓", category: F },
  { rawPattern: "黑莓", category: F },
  { rawPattern: "杨梅", category: F },
  { rawPattern: "椰枣", category: F },
  { rawPattern: "无花果", category: F },
  { rawPattern: "西梅", category: F },

  // === Chinese-common extension: whole grains ===
  { rawPattern: "糙米", category: G },
  { rawPattern: "燕麦", category: G },
  { rawPattern: "全麦面粉", category: G },
  { rawPattern: "全麦面包", category: G },
  { rawPattern: "荞麦", category: G },
  { rawPattern: "藜麦", category: G },
  { rawPattern: "玉米", category: G },
  { rawPattern: "小米", category: G },
  { rawPattern: "高粱", category: G },
  { rawPattern: "黑米", category: G },
  { rawPattern: "红米", category: G },
  { rawPattern: "薏米", category: G },
  { rawPattern: "薏仁", category: G },
  { rawPattern: "大麦", category: G },
  { rawPattern: "青稞", category: G },
  { rawPattern: "全麦", category: G },
  { rawPattern: "黑麦", category: G },
  { rawPattern: "莜麦", category: G },
  { rawPattern: "燕麦片", category: G },

  // === Chinese-common extension: legumes ===
  { rawPattern: "黄豆", category: L },
  { rawPattern: "绿豆", category: L },
  { rawPattern: "红豆", category: L },
  { rawPattern: "黑豆", category: L },
  { rawPattern: "鹰嘴豆", category: L },
  { rawPattern: "扁豆", category: L },
  { rawPattern: "蚕豆", category: L },
  { rawPattern: "毛豆", category: L },
  { rawPattern: "豆腐", category: L },
  { rawPattern: "豆腐干", category: L },
  { rawPattern: "豆皮", category: L },
  { rawPattern: "腐竹", category: L },
  { rawPattern: "豆浆", category: L },
  { rawPattern: "纳豆", category: L },
  { rawPattern: "豆豉", category: L },

  // === Chinese-common extension: nuts & seeds ===
  { rawPattern: "杏仁", category: N },
  { rawPattern: "腰果", category: N },
  { rawPattern: "开心果", category: N },
  { rawPattern: "榛子", category: N },
  { rawPattern: "夏威夷果", category: N },
  { rawPattern: "松子", category: N },
  { rawPattern: "碧根果", category: N },
  { rawPattern: "葵花籽", category: N },
  { rawPattern: "南瓜子", category: N },
  { rawPattern: "花生", category: N },
  { rawPattern: "芝麻", category: N },
  { rawPattern: "白芝麻", category: N },
  { rawPattern: "黑芝麻", category: N },
  { rawPattern: "亚麻籽", category: N },
  { rawPattern: "奇亚籽", category: N },
  { rawPattern: "核桃仁", category: N },
  { rawPattern: "核桃", category: N },
  { rawPattern: "栗子", category: N },
  { rawPattern: "瓜子", category: N },
  { rawPattern: "瓜子仁", category: N },

  // === Chinese-common extension: spices & herbs ===
  { rawPattern: "八角", category: S },
  { rawPattern: "花椒", category: S },
  { rawPattern: "桂皮", category: S },
  { rawPattern: "香叶", category: S },
  { rawPattern: "丁香", category: S },
  { rawPattern: "孜然", category: S },
  { rawPattern: "茴香", category: S },
  { rawPattern: "薄荷", category: S },
  { rawPattern: "罗勒", category: S },
  { rawPattern: "百里香", category: S },
  { rawPattern: "五香粉", category: S },
  { rawPattern: "十三香", category: S },
  { rawPattern: "咖喱粉", category: S },
  { rawPattern: "辣椒粉", category: S },
  { rawPattern: "胡椒粉", category: S },

  // === Chinese-common extension: animal products ===
  { rawPattern: "猪肉", category: A },
  { rawPattern: "牛肉", category: A },
  { rawPattern: "鸡肉", category: A },
  { rawPattern: "鸭肉", category: A },
  { rawPattern: "鹅肉", category: A },
  { rawPattern: "羊肉", category: A },
  { rawPattern: "鱼肉", category: A },
  { rawPattern: "虾", category: A },
  { rawPattern: "蟹", category: A },
  { rawPattern: "蛤蜊", category: A },
  { rawPattern: "扇贝", category: A },
  { rawPattern: "生蚝", category: A },
  { rawPattern: "鲍鱼", category: A },
  { rawPattern: "海参", category: A },
  { rawPattern: "鱿鱼", category: A },
  { rawPattern: "章鱼", category: A },
  { rawPattern: "黄鳝", category: A },
  { rawPattern: "泥鳅", category: A },
  { rawPattern: "牛排", category: A },
  { rawPattern: "排骨", category: A },
  { rawPattern: "里脊肉", category: A },
  { rawPattern: "鸡翅", category: A },
  { rawPattern: "鸡爪", category: A },
  { rawPattern: "鸭蛋", category: A },
  { rawPattern: "鹅蛋", category: A },
  { rawPattern: "鹌鹑蛋", category: A },
  { rawPattern: "奶酪", category: A },
  { rawPattern: "黄油", category: A },
  { rawPattern: "奶油", category: A },
  { rawPattern: "鳕鱼", category: A },
  { rawPattern: "鲈鱼", category: A },
  { rawPattern: "沙丁鱼", category: A },
  { rawPattern: "金枪鱼", category: A },
  { rawPattern: "鲑鱼", category: A },
  { rawPattern: "秋刀鱼", category: A },
  { rawPattern: "鲫鱼", category: A },
  { rawPattern: "草鱼", category: A },
  { rawPattern: "鲤鱼", category: A },

  // === Chinese-common extension: cooking oils ===
  // 一瓶油占重量大,plate 滤掉
  { rawPattern: "橄榄油", category: O },
  { rawPattern: "花生油", category: O },
  { rawPattern: "玉米油", category: O },
  { rawPattern: "菜籽油", category: O },
  { rawPattern: "芝麻油", category: O },
  { rawPattern: "香油", category: O },
  { rawPattern: "葵花籽油", category: O },
  { rawPattern: "葵花油", category: O },
  { rawPattern: "大豆油", category: O },
  { rawPattern: "色拉油", category: O },
  { rawPattern: "调和油", category: O },
  { rawPattern: "牛油果油", category: O },
  { rawPattern: "亚麻籽油", category: O },
  { rawPattern: "椰子油", category: O },
  { rawPattern: "黄油", category: O },
  { rawPattern: "酥油", category: O },

  // === Chinese-common extension: sugary drinks ===
  { rawPattern: "可乐", category: B },
  { rawPattern: "雪碧", category: B },
  { rawPattern: "芬达", category: B },
  { rawPattern: "橙汁", category: B },
  { rawPattern: "苹果汁", category: B },
  { rawPattern: "葡萄汁", category: B },
  { rawPattern: "柠檬茶", category: B },
  { rawPattern: "奶茶", category: B },
  { rawPattern: "冰红茶", category: B },
  { rawPattern: "王老吉", category: B },
  { rawPattern: "加多宝", category: B },
  { rawPattern: "汽水", category: B },
  { rawPattern: "苏打水", category: B },
  { rawPattern: "果味饮料", category: B },
  { rawPattern: "碳酸饮料", category: B },

  // === Chinese-common extension: processed meat ===
  { rawPattern: "火腿", category: P },
  { rawPattern: "培根", category: P },
  { rawPattern: "香肠", category: P },
  { rawPattern: "腊肠", category: P },
  { rawPattern: "午餐肉", category: P },
  { rawPattern: "热狗", category: P },
  { rawPattern: "肉松", category: P },
  { rawPattern: "肉干", category: P },
  { rawPattern: "牛肉干", category: P },
  { rawPattern: "猪肉脯", category: P },
  { rawPattern: "腊肉", category: P },
  { rawPattern: "火腿肠", category: P },

  // === Chinese-common extension: trans-fat snacks ===
  { rawPattern: "薯片", category: D },
  { rawPattern: "薯条", category: D },
  { rawPattern: "饼干", category: D },
  { rawPattern: "巧克力", category: D },
  { rawPattern: "糖果", category: D },
  { rawPattern: "雪糕", category: D },
  { rawPattern: "冰淇淋", category: D },
  { rawPattern: "甜甜圈", category: D },
  { rawPattern: "蛋挞", category: D },
  { rawPattern: "酥饼", category: D },
  { rawPattern: "桃酥", category: D },
  { rawPattern: "曲奇", category: D },
  { rawPattern: "威化", category: D },
  { rawPattern: "蛋黄酥", category: D },
  { rawPattern: "面包", category: R }
];
